# Generated by Django 4.1.4 on 2023-05-05 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostChirho',
            fields=[
                ('id_chirho', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title_chirho', models.CharField(max_length=140, verbose_name='Titulo de la publicación')),
                ('post_type_chirho', models.CharField(choices=[('computer_chirho', 'Computadoras'), ('gaming_chirho', 'Gaming'), ('monitor_chirho', 'Monitores'), ('notebook_chirho', 'Notebooks'), ('tv_chirho', 'Televisores')], help_text='Que tipo de publicación se desea hacer?', max_length=255, verbose_name='Tipo publicación')),
                ('post_chirho', models.CharField(max_length=400, verbose_name='Descripción de la publicación')),
                ('price_chirho', models.DecimalField(db_index=True, decimal_places=2, default=1, help_text='Precio de la', max_digits=8, verbose_name='Precio en $')),
                ('post_moment_chirho', models.DateTimeField(auto_now=True, null=True, verbose_name='Momento Publicado')),
                ('post_picture_chirho', models.ImageField(upload_to='publications_chirho')),
                ('user_chirho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
