# Generated by Django 4.1.4 on 2023-05-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_chirho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postchirho',
            name='post_picture_chirho',
            field=models.ImageField(upload_to='publications_chirho', verbose_name='Subir imagen'),
        ),
    ]
