# Generated by Django 4.1.4 on 2023-05-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_chirho', '0002_alter_postchirho_post_picture_chirho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postchirho',
            name='post_picture_chirho',
            field=models.ImageField(blank=True, null=True, upload_to='publications_chirho', verbose_name='Subir imagen'),
        ),
    ]
