# Generated by Django 4.1.4 on 2023-05-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_chirho', '0003_alter_postchirho_post_picture_chirho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postchirho',
            name='post_type_chirho',
            field=models.CharField(choices=[('computer_chirho', 'Computadoras'), ('gaming_chirho', 'Gaming'), ('monitor_chirho', 'Monitores'), ('notebook_chirho', 'Notebooks'), ('tv_chirho', 'Televisores')], max_length=255, verbose_name='Tipo publicación'),
        ),
        migrations.AlterField(
            model_name='postchirho',
            name='price_chirho',
            field=models.DecimalField(db_index=True, decimal_places=2, default=1, max_digits=8, verbose_name='Precio en $'),
        ),
    ]
