# Generated by Django 4.1.4 on 2023-05-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_chirho', '0004_alter_postchirho_post_type_chirho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postchirho',
            name='price_chirho',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=8, verbose_name='Precio en $'),
        ),
    ]
