# Generated by Django 4.1.4 on 2023-05-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_chirho', '0005_alter_postchirho_price_chirho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postchirho',
            name='post_chirho',
            field=models.TextField(max_length=400, verbose_name='Descripción de la publicación'),
        ),
        migrations.AlterField(
            model_name='postchirho',
            name='title_chirho',
            field=models.CharField(max_length=40, verbose_name='Titulo de la publicación'),
        ),
    ]
