# Generated by Django 4.1.4 on 2023-05-05 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_chirho', '0007_alter_postchirho_post_picture_chirho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postchirho',
            name='post_picture_chirho',
            field=models.ImageField(blank=True, null=True, upload_to='media/publications_chirho', validators=[django.core.validators.FileExtensionValidator(['gif', 'png', 'jpg', 'jpeg', 'webp'], 'Necesita poner archivos de imagen que terminen en gif, png, jpg, jpeg o webp')], verbose_name='Subir imagen'),
        ),
    ]
